import React, { useState } from "react";
import { useSelector } from "react-redux";
import styles from "./changelog.module.scss";

const changelogData = [
  {
    date: "April 26, 2026",
    title: "Edit comment fix, About page redesign, news external blog links, AI analysis fix, clearer game limit warnings",
    items: [
      "Forum: the edit icon (✏) on comments now works correctly — clicking it opens the inline edit form. Previously it failed silently due to a mismatch between the button and the state it was setting",
      "About page: redesigned with panel cards matching the rest of the site. Mission and Team sections use bordered cards; Future Goals now displays as a responsive icon grid",
      "News: articles can now link to an external blog post (e.g. a Lichess blog). The preview card automatically fetches the page's title, description, and banner image so readers can see what the link is about before clicking. The link label (e.g. 'Lichess Blog Post', 'Official Announcement') is now customisable per article",
      "When you hit a game limit (correspondence, live, open match, or anonymous), a modal now pops up with a clear explanation of the cap, why it exists, and what to do next. The current count and maximum are displayed prominently. Buttons let you jump straight to your ongoing games so you can resign or check them quickly",
      "Admin portal — AI Training: clearing a job's data now immediately updates the analysis summary. Previously, deleted training data could still appear in the AI analysis totals until an admin manually clicked Regenerate",
    ],
  },
  {
    date: "April 25, 2026",
    title: "Forced capture display fix, initial-state scan fix, leaderboard speed, AI training data management, AI engine special-squares support",
    items: [
      "Game cards and game detail page: Forced Capture is no longer listed under Win Conditions — it is a movement mechanic, not a win condition. It now appears in the Special Rules section of the game detail page instead",
      "Wizard review step: Forced Capture now appears under Special Rules instead of Win Conditions",
      "Admin portal — Initial-state scan: games with no pieces placed and no piece-placement action enabled are now correctly flagged as invalid (previously they were silently skipped)",
      "Global leaderboard: page now loads faster — the player count and player list queries now run in parallel instead of sequentially",
      "Admin portal — AI Training: added a '🗑 Clear Data' button per job. Deletes the on-disk log and model files and resets the game count to 0. The job record is kept in history. Only shown for non-running jobs that have training data",
      "AI engine: Control Squares win condition now works in AI training — games correctly end when a player holds enough control squares for the required number of turns. MCTS rollouts now bias moves toward control squares so training converges. Stalemate-Win and No-Moves-Loss conditions are also now honoured during MCTS rollouts",
      "AI engine: MCTS rollouts now understand all special square types — promotion squares (strong bias for promotable pieces), range squares (positional bias for landing on squares that boost movement range), and custom squares (composite squares combining multiple effects). Promotion square detection also fixed in move generation to use the game's configured promotion squares instead of only the back rank",
      "Admin portal — AI Training: anti-chess wins (Lose All Pieces), Stalemate Win, No Moves Loss, Capture Condition, and Control Squares wins are now all tracked and displayed separately in the win breakdown — previously they collapsed into 'other'. Control Squares games also now display 'win (control squares)' in the training log instead of 'P1 wins by win'",
    ],
  },
  {
    date: "April 23, 2026",
    title: "Link insertion, live game note, stale game cleanup, AI Analysis request button, admin tools polish",
    items: [
      "Piece detail page now describes first-move-only restrictions next to ratio movement, step-by-step movement, custom movement, and ranged attack — matching the purple highlighting on the board preview.",
      "Game detail page now lists each piece's custom movement and custom attack squares as compact [row, col] arrays in the Piece Settings section.",
      "Announcements page now shows the full announcement text instead of cutting off after 280 characters. The Optional Link URL field has been removed — admins can insert specific gridgrove.gg links directly into the body via the 🔗 button instead. All announcement notifications now also render those inserted links as clickable.",
      "Bots can now place pieces in Othello-style games and prioritize placements in piece-count win-condition games.",
      "Match history now shows piece-count win and equal-piece-count draw reasons in plain English.",
      "Live game cap: each user can be in at most 8 live games at a time (4 for anonymous players). Correspondence cap: 24 (12 for anonymous). Challenge and open-match caps also added.",
      "Text areas across the site (forums, comments, game descriptions, piece descriptions, announcements, news, careers, and user bios) now support clickable links to gridgrove.gg pages. Use the 🔗 link button that appears below the text area to insert a link — you can give it a custom display label. Only gridgrove.gg links are supported at this time",
      "Match history: promoted pieces now display correctly when you replay past games. Previously a promoted pawn would still appear as a pawn for the rest of the replay; the replay board now swaps in the promoted piece on the move it promoted. The text move list also shows promotion notation (e.g. 'e7-e8=Q')",
      "Match history: games that ended on the initial position now show a clear reason ('by initial position — no rating change') in both the match list and the match detail page, instead of the generic 'won by game complete' / 'the game ended in a draw'",
      "Live game: if a game ends on the initial position, the game-over modal now reliably appears (previously the modal could be missed if you joined just as the game ended, since joinGame and gameOver fired back-to-back). Reloading a completed game also re-displays the modal",
      "Live game: regular randomized games now use the same re-roll guard as the bot path — if a roll lands on an already-decided position the server re-shuffles up to 12 times (with a 🎲 banner) before falling through to the initial-position safety net",
      "Forums: General and Game forum lists now paginate correctly — page totals reflect only the visible category instead of the entire articles table (no more empty pages)",
      "Forums: new category system. When creating a forum from /forums/new you can choose a category (General, Gameplay, Social, Bug Report, Feedback, Announcement, or Misc). The category appears as a pill on the General forum list and on the forum's detail page. Game forums always use the 'Game' category automatically",
      "Forums: 'Created At' column replaced with 'Last Comment' (showing the most recent commenter and timestamp). Forums are now sorted automatically by most-recent activity, so live discussions stay near the top",
      "Forums hub: the 'Create New Post' button still goes to /forums/new and now creates a post in the General forums section by default",
      "Initial Position Scan: now considers piece-placement actions (e.g. Othello-style 'place a piece' moves) when checking for legal moves, fixing false 'no legal moves' / 'starts in checkmate' reports on placement-based games",
      "Initial Position Scan: games whose fixed starting position has two pieces stacked on the same square now report a clear 'two pieces share the same square' error instead of a misleading checkmate warning",
      "Initial Position: if a brand-new game's starting position is already a checkmate, stalemate, or other decided state, the live game now ends immediately with reason 'Initial Position' and ELO is not affected for either player (previously the player with no moves would eventually time out and lose rating)",
      "Game wizard: published games are now checked at save time to make sure the starting position isn't already a win, loss, or draw. If it is, a warning explains the issue and the game can't be saved as published until you change it. Drafts are not affected so you can keep iterating",
      "Live games with randomized starting positions: if a roll happens to produce an already-decided position (e.g. a side that is in checkmate before move 1), the server automatically re-rolls (up to 12 times, never repeating the same roll) and shows both players a brief 🎲 banner explaining the re-roll",
      "Game detail page: a red banner now appears at the top of any game whose starting position is already decided, asking the creator to fix it",
      "Admin dashboard: new 'Initial Position Scan' tab — runs a one-time check across every published game, lists any that begin in a decided state, and links straight to each game's detail page",
      "Play page — Live Games section: added a note recommending Correspondence games while the player base grows, and explaining the 24-hour stale-game rule",
      "Live games where both players have joined but no moves have been made are now automatically cancelled after 24 hours — no ELO is affected. Open matches (waiting for a second player) are not affected",
      "Game detail page: added a 'Request AI Analysis' button (visible to the game creator and admins) that appears when no analysis exists yet. Pressing it sends a notification to the site owner with a direct link to start training for that game",
      "Admin dashboard — AI Training Analysis: game-type dropdown now defaults to 'trained games only', showing how many of your total games have training data. Uncheck the filter to see all games",
      "Admin dashboard — AI Training Analysis: visibility buttons (Admins only / Creator + admins / Public link) are now clearly labeled with icons and tooltips explaining what each option does. The active setting is highlighted in green",
      "Admin dashboard — Anonymous Games: added a 'Moves' column showing the total move count per game, and a Refresh button to reload the list without switching tabs",
      "Admin dashboard — Initial Position Scan: fixed a bug where clicking the scan would return a 403 error (the wrong auth token was being read from storage)",
      "Home page: featured games now show their real play count instead of always showing '0 games played'",
      "Performance: forums list now loads significantly faster — previously loaded each forum's comment count, like count, author name, and game name with separate database queries (up to 81 queries for a page of 20). All of this is now resolved in 2 queries using SQL joins",
      "Performance: opening a forum post now loads comments with author names in a single query instead of one query per comment",
      "Performance: game detail page now fetches the forum link and upvote count in parallel instead of sequentially",
      "Announcements: each card now has a 'View announcement' button that goes directly to the announcement detail page. If the announcement has an optional link, clicking the body text navigates to that link. Admins can now edit announcements inline on both the list page and the detail page",
      "Notifications: announcement notifications now show the full announcement text instead of cutting it off. Editing an announcement also updates the text in everyone's existing notifications. A 'View Announcement' button now appears on announcement notifications. A 'View all announcements' shortcut link has been added to the top of the notifications page",
      "Notifications: fixed notification wording for new games — changed 'Username created a new X game' to 'Username started a game of X', consistent with the notification title",
      "Play page — game cards: rated/casual badges now also appear on correspondence games, matching the live-game cards",
      "Admin dashboard: new 'Private Games' tab listing every active game whose host disabled spectating. Read-only — admins cannot watch these games per the host's choice",
      "Announcements: delete button is now restricted to the site owner only. Regular admins can still post but cannot remove announcements",
      "Admin dashboard: fixed a flash of 'No users found' when first loading the Users tab or switching tabs before data arrives",
      "AI Training: training jobs that were stopped due to running out of memory now automatically resume with a higher memory limit (50% more, rounded up to the nearest 256 MB) so they don't hit the same ceiling again",
      "Live game: spectators are no longer shown while the game is in the lobby / waiting for players. The spectators list only appears once the game has actually started",
      "Live game: players in a match are no longer incorrectly listed in the spectators panel for their own game",
      "Comments and forum posts: clicking an emoji in the emoji picker now immediately inserts it into the text field and closes the picker",
      "Notifications: clicking a win/loss result notification now takes you directly to the match detail page instead of your profile",
      "Live game clocks: fixed an issue where playing as Player 1 against the computer caused the clock to only visually update on each move instead of ticking down in real time",
      "Admin dashboard — AI Training: the 'Show trained games only' filter now correctly includes game types with any training data, not just those with a fully completed job",
      "Live game vs computer: offering a draw during the computer's thinking delay is now handled immediately — the game ends right away instead of waiting for the computer to finish computing its move",
      "Performance: game detail pages for games that have published AI analysis now load noticeably faster — the page no longer pulls down the full analysis snapshot just to decide whether to show the link to it",
      "Performance: the admin AI-training panel and the Adaptive-bot availability check on the Play page do far less disk I/O when polling running training jobs, which should reduce CloudWatch IOPS alarms on the trainer instance",
    ],
  },
  {
    date: "April 22, 2026",
    title: "Adaptive AI Computer Opponent, Trainer Moved to Frontend EC2, Resume & Pause Training Controls",
    items: [
      "Play page — game cards: added a per-game move counter under the rated/casual badge on every live game in progress. Auto-refreshes every 5 seconds while the tab is open",
      "Play page — game cards: rated/casual badges (and the new move-counter) are now all the same width, with a little breathing room between the time-control pill and the badges below it",
      "Play page — game cards: usernames are now clickable links to each player's profile, stacked vertically on separate lines with a stylized '⚔ vs' between them instead of a single comma-free line",
      "Host Game modal: the 'Additional Options' popover now closes automatically when you click outside of it, and each option's explanation has moved into a hover tooltip (ℹ️) next to the label to save vertical space",
      "AI self-play / training: added full draw-rule enforcement in the self-play loop so games no longer run up to the 400-move trainer cap as often: n-fold repetition (when the variant defines one), the 50-move / nth-move drawing rule, stalemate, and a royals-only insufficient-material draw for checkmate-only variants all now fire as real game-ending reasons",
      "AI self-play / training: the fallback we used past 400 moves is now an aggressive capture-biased rollout with a 'advance toward the far edge' heuristic for non-capture moves, instead of a random rollout. In practice the rule checks above almost always end the game first; this path is only for exotic variants that don't define any drawing rule",
      "Live games — sounds: removed the separate premove-set sound effect. Now when you queue a premove nothing plays on setup, the regular move sound plays when the premove actually executes, and nothing plays if your premove is invalidated by the opponent's move",
      "Announcements and AI Analysis pages: restyled for the dark theme (previously used light-mode colors that were unreadable on the site background)",
      "Admin dashboard — AI Training: when running the trainer locally (dev mode), each completed job row now shows a Download button that packages the job directory as a ZIP, so devs can train offline and upload the result into the live admin portal",
      "AI Analysis report: the two-column 'Side 1 / Side 2' breakdown is now labeled 'Player 1 / Player 2' to match the rest of the site's terminology",
      "AI Analysis: report now excludes games from training runs that pre-date draw/end-reason tracking by default (those older games all reported as 'unknown draws' and skewed the numbers). Admin generator has a toggle to include them if needed; a line in the sample-size block notes how many were excluded",
      "AI Training: fixed self-play games for checkmate-only game types reporting a decisive 'won by royal piece captured' result when in fact the game ran past the trainer's 400-move cap. The royal-capture heuristic the rollout uses for speed is invalid for those games (their rules don't allow capturing a royal piece), so the outcome is now reported as an indeterminate draw by trainer move cap — matching how the real game would have ended in that situation",
      "New 'Announcements' channel: site-wide updates from the GridGrove team. Posting an announcement (admin-only) creates a one-time notification for every active user and adds a paginated entry to the new Announcements page (linked from the Info hub)",
      "Admin dashboard — AI Training: per-game-type AI Analysis report. Admins can generate a balance summary (per-player win rate, draw type breakdown, sample size, and an overall imbalance verdict) for any trained game and publish it as private (admins only), creator-visible (game creator + admins), or public (shareable link). When you can view it, a '📊 AI Analysis' button appears next to Play on the game detail page",
      "AI Training: the trainer now records why each game ended (checkmate, stalemate, move-limit rule, royal capture, etc.) instead of treating every non-checkmate as 'winner: null'. The admin live-progress lines now read e.g. 'Game 47: draw (stalemate) — 30 moves' instead of dumped JSON, and the new AI Analysis report uses these reasons to break down draws by type",
      "Game detail page: fixed per-piece directional ranged-attack descriptions reading the wrong field name (e.g. 'up_attack' instead of 'up_attack_range'), which caused every direction-ranged piece to show the generic 'has a ranged attack' fallback instead of the actual per-direction attack ranges",
      "Admin dashboard — AI Training: new 'Upload pre-trained artifacts' panel. Admins can train on a dev machine (or any other host with the Rust trainer built) and upload either a raw book.jsonl or a zip of an entire job directory. Uploaded data is automatically merged with everything already gathered by cloud training — uploads stack on top of existing data instead of replacing it. The panel includes step-by-step local-training instructions and uploaded jobs are tagged with an 'uploaded' badge in the jobs list",
      "Adaptive bot now consults book data merged across ALL training jobs for a game type, not just the most recent run. Re-training (or uploading additional artifacts) now adds to the bot's knowledge instead of overwriting it",
      "Fixed: when training runs on a separate EC2 instance from the backend (the new default), the adaptive bot's opening book is now correctly fetched from the trainer-service. Previously the backend was reading its own empty filesystem and falling through to plain search instead of using the trained book",
      "New 'Adaptive' computer difficulty: when training data exists for a game type, a fourth difficulty option appears next to Easy / Medium / Hard. The Adaptive bot consults an opening book built from self-play training (it picks the move with the best win-rate from positions the trainer has seen, and falls back to a deeper search when out of book). The button only appears for game types that have training data, with a 'Trained on N games' subtitle so you can tell at a glance how much it knows about the variant",
      "Adaptive bot baseline is now always at least as deep as Hard (depth 5 / quiescence 5), and gets stronger as more training games accumulate (depth 6 at 500+ games, depth 7 at 2,000+)",
      "Admin dashboard — AI Training: training jobs can now run on the frontend EC2 instance via a new trainer-service proxy. The backend still serves all admin UI calls, but the actual Rust subprocess runs on the larger frontend box (more RAM, more CPU credits) so training never competes with live-game traffic on the smaller backend instance",
      "Admin dashboard — AI Training: jobs that were stopped, interrupted by a server restart, failed, or aborted by the RAM cap can now be resumed with a one-click Resume button. The resumed job picks up from the last completed game, refreshes the rules dump (in case the game was edited), and re-derives a deterministic seed so progress is reproducible",
      "Admin dashboard — AI Training: new Pause Training / Resume Training control. While paused, new training jobs (and resumes) are rejected with a clear message; in-flight jobs continue. There's also a separate webhook endpoint a CloudWatch / Lambda alert can call to auto-pause when the host's CPU credit balance gets low (so we never throttle the live site)",
      "Admin dashboard — AI Training: default RAM cap raised from 1 GB to 2 GB now that the trainer runs on the frontend EC2 (4 GB total)",
      "Admin dashboard — AI Training: significant performance fix in the trainer's MCTS rollouts. After the earlier royal-piece detection fix, rollouts were paying for full legality checks on every move which made each self-play game ~10x slower than expected. Rollouts now use pseudo-legal moves with royal-capture short-circuiting, so games complete in roughly the original time while still ending on real checkmates",
      "AI Training internals: the Rust trainer now writes an opening book during self-play (book.json) summarising every position seen in the first 20 plies of every game with the move that won most often from that position. The Adaptive bot reads this on each move",
    ],
  },
  {
    date: "April 21, 2026",
    title: "Admin Donor Badges, Rated/Casual Badges on Game Cards, Stricter Name Moderation & Clock Improvements",
    items: [
      "Admin dashboard — AI Training: fixed three bugs that made early training runs look broken. (1) Self-play games for chess-style game types were finishing with no winner because the trainer wasn't recognizing the King as a royal piece — checkmate detection now correctly reads the per-placement royal flags (the same data the live game uses), so games end on real checkmates instead of always running to the move cap and reporting a draw. (2) The progress counter on each job in the training list now updates live (was previously stuck at 0 / N until the job finished) by reading from the per-job log on each refresh. (3) Bot games now respect the host's randomization mode (Pieces, Rows, etc.) — the randomization step was previously skipped for vs-computer games because the bot bypasses the normal join flow",
      "Admin dashboard — new 'AI Training' tab: admins can now kick off self-play training runs for any game type. Training runs as a sandboxed background process with a configurable RAM cap (default 1 GB) and is restricted to a single CPU core, so it cannot impact the live game server. Progress, recent events, and a stop button are visible per job. The trainer now understands the full piece-rules surface (8-direction movement & capture, exact distances, available-for-N-moves, additional-movements, capture-only directions, ratio jumps with selective hopping, repeating ratio, both-side castling with the check-rule path safety, custom movement/attack squares, multi-tile pieces, range-square bonus, and custom-square first-move blockers), so adaptive AI for non-chess games will train against the actual rules of those games instead of a chess-only stand-in. The cached rules dump is also auto-refreshed whenever a game or piece is created/edited, so training always sees the latest configuration",
      "Admin dashboard — Donor Badge: admins can now manually grant or adjust donor badges for Venmo / Cash App contributors from the Users tab (enter the payment amount to award Silver or Gold status, or set to 0 to remove a badge)",
      "/play page — game cards now show a 'Rated' or 'Casual' badge so you know before you join whether ELO is on the line",
      "/play page — clicking the game title on any game card now links to that game's detail page; clicking a host's username links to their profile",
      "Live games — disconnect banner: the Pause / Resume timer button is now hidden once the game has already ended by disconnect, since the timer is no longer active",
      "Live games: removed the leftover 'Custom' entry from the board legend when a game has no custom squares — the legend no longer shows categories that aren't in use",
      "Live games: fixed a bug where bot games sometimes showed 'Starting…' under the title even after the game was already in progress; the status now correctly reads 'In Progress'",
      "Live games: the 'Your turn' / 'Waiting for opponent' indicator is now centered above the board (in its own column of the game header) so it's always easy to glance at, regardless of how long the game title is",
      "Live games — disconnect banner: the warning banner that appears when an opponent disconnects (with the countdown to your win, plus the Pause Timer / Restart Timer buttons) is now shown at the very top of the game page so it's impossible to miss, instead of being tucked above the board",
      "Live games — clock overhaul: the server now ticks player clocks at 100ms precision and uses exact wall-clock time deltas. Two specific bugs are fixed: (1) when the bot's AI computation blocks the server event loop for 1–3 seconds, the next timer tick used to deduct that entire blocked period from whichever player was active at that moment — which after a bot move was the human, so the human's clock would visibly drop by a couple of seconds. The timer now detects when the active player has changed (or when an unusually long blocking pause occurred) and re-anchors instead of charging the wrong player. (2) Periodic 1-second 'time sync' broadcasts during a game caused the displayed clock to jump backward each time, because network latency made each broadcast slightly stale. Those periodic broadcasts have been removed entirely — the authoritative clock value is now sent only on each move and at game end, and the client interpolates smoothly in between, so there's no longer any 'snap' on every tick. Combined with the existing sub-second bot AI deduction (which fixes the bot's clock appearing to round up), live game clocks now behave like standard competitive chess clocks",
      "Live games — last-move highlight persistence: the previous move's from/to highlights now stay on the board for 1 second after a new move is made, fading out smoothly. The fade only affects the dashed outline (on the from square) and the colored highlight overlay (on the to square) — the piece graphics themselves and the underlying board squares stay fully opaque so they don't appear to blink. New Preferences toggle 'Persist last-move highlight' under the Animations section lets you turn this off if you prefer the old instant-clear behavior. On by default",
      "Preferences: the Donor Badge and Messaging & Chat sections have been merged into a single 'Privacy' section, since all of those toggles (hide donation badge, allow non-friend DMs, disable game chat, public chat for spectators, show computer games publicly) control privacy settings",
      "Preferences: toggle switches are now perfectly pill-shaped (fully rounded ends) to match the rest of the site's UI",
      "Inbox: fixed a bug where sent messages occasionally appeared twice in the conversation view (a refresh would correct it); the client now de-duplicates messages by ID so you'll never see the same message added to the conversation twice",
      "/play page: fixed a bug where deleting a game (admin-only on each game card) would briefly flash the card but leave it on screen until a manual refresh — particularly visible in the Computer Games section. Deleted cards now disappear instantly across all sections (Open, Ongoing, Private, Computer Games) by both optimistic UI removal and a refetch of the affected lists",
      "Piece detail page: the Ranged Attack section now explicitly shows whether the piece can fire over enemy pieces and whether it can fire over allied pieces (or whether it's blocked by them)",
      "Piece detail page: the 'Can Castle' badge now also displays the configured castling distance (in squares)",
      "Piece detail page: step-by-step movement, capture, and ranged attack entries now label themselves as 'Manhattan' (orthogonal only) or 'Chebyshev' (any direction including diagonals), so you can tell at a glance which counting rule applies",
      "Game detail page: the Piece Settings section now describes ranged attacks for any piece that has them — including direction/range, ratio (L-shape) and step-based ranged patterns, the per-attack capture cap, the repeat-attack flag, and whether the attack can fire over enemies / allies. It also lists Hop Capture (with chain-capture indicator) and Ally Capture for pieces that have those abilities",
      "Game and piece names are now held to a higher professional standard — names containing sexual orientation terms, political figures or movements, drug references, explicit sexual content, or related categories are automatically flagged and held for moderator review before becoming publicly visible",
      "Flagged games and pieces still get created normally; you'll receive a notification once a moderator approves or rejects the name. Your item remains visible to you in your personal library during the review window",
      "The auto-created discussion forum for a flagged game is also held as private until the game name is approved",
      "Admins have a new 'Name Reviews' tab in the Admin Portal to approve or reject flagged names, with full details on which words triggered the review",
      "New Admin Portal column: 'Last Active' on the Users tab shows each user's most recent activity timestamp formatted in your local time as MM/DD/YYYY h:mm am/pm",
      "Fixed the Leaderboard tile on the Community Hub — the link was pointing at /leaderboard instead of the actual route /community/leaderboard, so clicking it would 404",
      "Donate page: replaced the generic 'industry-leading providers' note with a clearer message about how donations are processed and that we never see or store your payment details",
      "Donate page: added two new ways to give — Venmo (@GridGrove) and Cash App ($GridGrove). Each option shows a tappable card that opens its scannable QR code in a popup, with a fallback link that opens the Venmo or Cash App page directly",
      "Custom Squares (Step 3) — two new optional behaviors:",
      "  • 'Restrict First-Move Abilities to These Squares' — when set on any custom square in the game, all first-move-only / available-for-first-N-moves abilities (e.g. a pawn's two-square first move) are disabled everywhere except on custom squares with this flag. This makes it possible to model classic-chess pawn behavior where the double-step is only legal from a specific rank",
      "  • 'Disable First-Move Abilities On This Square' — the inverse: while a piece is standing on a custom square with this flag, all of its first-move-only / available-for-first-N-moves abilities are unavailable",
      "Both new toggles save with the rest of the custom square configuration, carry over via the Fill Entire Row helper, are described on each game's detail page in the Custom Squares section, and are enforced in live games (move generation, capture options, and additional-direction moves)",
      "The two new first-move flags are now mutually exclusive — toggling one off automatically disables the other (and the off one is greyed out while the other is on)",
      "All Custom-Square configuration switches (Acts as Range / Promotion / Control, plus the new first-move toggles) and the Control-Square configuration switches (Require Consecutive Turns, Require Specific Piece Type) are now true toggle switches with hover-able info tooltips, instead of plain checkboxes with inline help text",
      "Special Squares (Step 3): two new buttons next to 'Clear All Special Squares' — 'Mirror Bottom → Top' and 'Mirror Top → Bottom'. Each one copies every special square (range, promotion, control, custom) — including all per-square settings (range bonus, control turn requirements, applies-to-player, custom flags, etc.) — from one half of the board to the other. The middle row is automatically excluded on odd-height boards. Useful for symmetric setups",
      "Donate page: Venmo and Cash App card colors muted slightly to match the rest of the donate page's palette",
      "Donate page: added a clear note to the Venmo / Cash App section explaining that those services don't expose a public payment-confirmation API, so donor badges from those methods are awarded once we can manually verify the payment. Badges are calculated from the amount you sent (not the amount we receive after processor fees on business accounts), and contact support if your badge hasn't appeared within a day or two",
      "Database: bumped game_types.special_squares_string, range_squares_string, promotion_squares_string, and control_squares_string from VARCHAR(1000) / TEXT to MEDIUMTEXT (16MB). The previous limit was overflowing on large boards with lots of custom squares (the error was 'Data too long for column special_squares_string' on save). Auto-applied on server restart via the migrations runner",
      "Computer player fix: the AI was unable to make any moves on games that used the new 'Restrict First-Move Abilities to These Squares' setting (it was treating the restriction as 'block ALL moves' for any piece not standing on a flagged custom square instead of just blocking first-move-only abilities). Pieces with no first-move-only abilities now move normally regardless of where they stand",
      "Live games: the 'Show promotion squares' toggle has been replaced with a unified 'Show all special squares' toggle that lights up every special-square type on the board (promotion, range, control, and custom) with a colored overlay and a letter badge (P / R / C / combined). By default no special squares are highlighted in live games — toggle it on when you need to see them",
      "Game detail page: custom squares with identical configurations are now grouped onto a single line (e.g. '[a2, b2, c2, d2] — Range Boost (+1) + Promotion') instead of repeating the same description on a separate line for every square. The custom-square description text was also rewritten to spell out the new first-move ability gating",
      "Game detail page: legend now correctly says 'Custom' (not 'Special') when the symbol refers to user-configured custom squares",
      "Step 4 piece placement: right-clicking an empty square now pre-selects the most recently placed piece in the modal — including all of its previous settings (player, image, HP/AD, control flags, promotion options, castling overrides, etc.). Faster placement of repeating pieces",
      "Undo (Ctrl+Z / Cmd+Z) is now wired up across the wizards: in the Game Wizard's Step 3 (special squares — placement, removal, drag-and-drop, mirror, fill-row, clear all) and Step 4 (piece placement, drag-and-drop, mirror, clear all), and in the Piece Wizard's Step 2 / Step 3 custom movement and custom attack square selectors (paint strokes and clear-all). Standard Ctrl+Z text editing inside form fields still works natively — the wizard-level undo only kicks in when focus is outside a text input",
      "Game Wizard: when going from Step 3 to Step 4, the wizard now warns you if you placed both 'Restrict First-Move Abilities to These Squares' and 'Disable First-Move Abilities On This Square' on the same board (these are mutually exclusive in spirit; the modal explains the conflict and lets you go back to Step 3 to fix it)",
      "Live games — clock jump fix: the on-screen clock no longer 'jumps backward' for a moment right after a move was made. The client now re-anchors its local clock interpolation to the authoritative server-reported player times every time a move event arrives, so the visible clock is always smooth between server ticks",
      "Live games — human-vs-human clocks now tick smoothly once per second (previously they would only update at the end of each turn, in a single lump-sum deduction). The fix that was already in place for games against the computer now applies to games against other players too",
      "Live games — disconnect banner restyle: the gradient red/orange disconnect banner is now a single solid red color with no warning icon, and the text is more concise ('X disconnected. You win in Ns.' with simpler 'Pause' / 'Resume' buttons)",
      "Live games — leaving the game page now starts the disconnect-forfeit countdown: if you navigate away from a live game (instead of closing the tab entirely), your opponent will now see the same disconnect banner and grace-period countdown as if your connection had dropped. Coming back to the game page automatically cancels the timer. Bot games are unaffected",
      "Piece Wizard — fixed an edit bug where opening an existing piece that has any ranged attack values (directional, ratio, etc.) was leaving the 'Enable ranged attack' toggle unchecked. The toggle is now correctly pre-checked for any piece with non-zero ranged-attack data",
      "New win condition — Win by Disconnect: if your opponent loses their internet connection during a live human-vs-human game, a countdown timer now starts. If they don't return in time, you win automatically (and ELO is awarded as if it were a normal win in rated games). The grace period scales with the time control: 15 seconds for time controls under 30 minutes, 30 seconds for 30–59 minutes, and a full minute for 60+ minute or untimed games. The remaining player sees a banner with a 'Pause Timer' button (to grant your opponent more time) and a 'Restart Timer' button (to give them a fresh countdown if you'd rather close out the win quickly). Match histories now display 'win/loss by disconnect' for these results",
      "/play screen — new 'Computer Games' section that lists your ongoing games against the computer with a Resume button, paginated like the other lists",
      "/play screen — new Preferences toggle 'Show my computer games publicly': when enabled, your ongoing games against the computer become visible in the public Live Games list so others can spectate. Off by default",
      "/play screen — every section header (Game Types, Incoming Challenges, Private Games, Online Friends, Open Matches, Live Games, Computer Games, Correspondence Games) is now collapsible by clicking its title. All sections are open by default; collapse state is remembered in your browser between visits",
    ]
  },
  {
    date: "April 20, 2026",
    title: "Range-Square Bonus, SVG Auto-Scan, Moderation Notifications & Admin Audit Log",
    items: [
      "Promoted pieces no longer let opponents \"win early\" — when a pawn (or any other promotable piece) is promoted into a piece type that's flagged 'End game on capture' or 'End game on checkmate' in the game's piece configuration, the promoted piece now correctly inherits those flags. Combined with the existing 'Require ALL capture-flagged pieces to be captured' option, this means a custom king-of-the-hill style game with multiple required-capture pieces no longer ends just because the two original kings were captured while promoted kings still stand on the board",
      "New Win Condition option: 'Require ALL checkmate-flagged pieces to be checkmated' (under the Checkmate Condition in the game wizard, Step 2) — when enabled, every piece flagged 'End game on checkmate' must be simultaneously under lethal attack with no legal escape, AND capturing one such piece does not end the game until none remain. This pairs with promotion to make games arbitrarily hard to finish (e.g., promote pawns into more kings to keep the game going)",
      "Range Squares can now be configured with a per-square range bonus from +1 to +8 (default +1). Click any range square in Step 3 to set the value, and the bonus carries over when you use Fill Entire Row. The chosen bonus is applied in live games — pieces standing on a Range Square gain that many extra squares of movement, capture, and attack range — and the value is described on each game's detail page",
      "Custom Squares with Range behavior are now also capped at +1 to +8 (down from the previous max of +10) so they line up with plain Range Squares; backend validation re-clamps the value so a hand-crafted request can't bypass the cap",
      "Control Squares: the per-square 'Require Specific Piece Type' toggle now actually takes effect in live games — when enabled, only pieces marked 'Can Control Squares' in Step 4 can hold the square; when disabled, any piece can hold it. The configured turns / consecutive-turns / applies-to-player / piece-requirement settings now also appear on the game detail page so opponents can see them up front",
      "You'll now get a notification when a moderator approves or rejects one of your pieces (and the notification deep-links to the piece or your library so you can re-upload if needed)",
      "SVG piece images now get auto-moderated instead of always going to manual review: SVGs containing scripts, iframes, foreignObjects, inline event handlers, javascript: URLs, or XML entities are rejected outright (XSS protection); SVGs containing embedded raster images or external image references are queued for manual review; plain shape-only SVGs are auto-approved. This dramatically reduces the moderation queue for chess-piece SVG uploads",
      "Image upload size limit reduced from 5MB to 2MB for both piece images and profile pictures — pixel-art and SVG pieces never need more than that, and the lower cap keeps page loads snappy",
      "Server Stats Memory Stats endpoint now actually loads — a catch-all `/api/*` handler had been registered above it and was swallowing the request; the catch-all has been moved to the bottom of the route list so the real endpoint is reachable",
      "New Admin tab: 'Deleted Users' shows an audit log of every account deletion (self-delete or admin-initiated) including the deletion timestamp, previous username, original user ID, and who initiated the deletion",
      "Anonymous games now get cleaned up automatically — any anonymous game still in 'waiting' / 'active' / 'ready' state for more than 24 hours is closed (status='completed', end_time set) and any anonymous game older than 30 days is permanently deleted; this prevents abandoned anonymous matches from accumulating forever",
      "Leaderboard is now paginated (25 players per page) with previous/next and numbered page buttons, instead of trying to load every account in the database in a single request",
      "Fixed a crash on the Edit Account page when an admin/owner edited their own profile — submitting the form was throwing 'Cannot read properties of null (reading id)' because admin self-edits never populated the secondary user lookup; the form now falls back to the logged-in user's id in that case so admins can update their own bio, linked Chess.com / Lichess accounts, etc.",
      "Admins and owners can now spectate any game from the Admin Portal, even ones that have spectators disabled",
      "Backstop for completed games with a missing end_time: the cleanup job now also fills in end_time on any 'completed' game where it ended up NULL (using the game's start_time / created_at as the fallback), so the audit field is never blank on a finished match",
      "CRITICAL FIX — duplicate win/loss notification spam: a recursion bug in the game-over broadcaster (broadcastGameOver was calling itself instead of emitting the socket event) caused the server to throw 'Maximum call stack size exceeded' and, because the error was caught at every recursive frame, fire thousands of duplicate win/loss notifications per game. The broadcaster now emits the socket event directly, refuses to broadcast the same game twice (in-memory guard), and the cleanup job deletes any duplicate game_outcome notifications already in the database (keeping only the earliest per user/game)",
      "Homepage 'featured games' preview boards load much faster: removed an unnecessary LEFT JOIN + COUNT against the entire games table for hand-picked featured games (we don't need play_count for those), and the per-game-type piece queries now run in parallel instead of one at a time",
      "Stalemate detection in bot games is now consistent with player-vs-player games: previously the bot move handler only checked stalemate when 'mate_condition' was enabled and always treated stalemate as a draw — so a pawn-only game with 'stalemate_win_condition' set would never end after the bot's move even when you had no legal moves left. The bot path now mirrors the human path: it checks stalemate independently of mate_condition, and properly awards the win to the stalemated player when stalemate_win_condition is set, ends in a draw when stalemate_draw_condition is set, or skips the turn when neither rule applies",
    ]
  },
  {
    date: "April 19, 2026",
    title: "Stalemate Fixes, Capture Win Persistence & Custom Square Combinations",
    items: [
      "You'll now get a notification whenever a game you're in ends — 'You won against ___' or 'You lost to ___' — and the notification links to your match history so you can review the game",
      "You'll also get a notification when another player joins a game you created (the notification links straight to the game)",
      "Admin endpoints are now exempt from the general API rate limit so the Server Stats panel and other admin tools can poll freely without getting blocked",
      "Server Stats panel now shows the actual server message (including 'Too many requests') when the endpoint returns something unexpected, instead of a vague 'JSON without expected fields' error",
      "You can now link your chess.com and lichess.org accounts from your Edit Account page, and a new 'Connected Accounts' card on your public profile shows the linked usernames as clickable links to those external profiles",
      "Bios, comments, forum posts, game descriptions, game rules, and piece descriptions now allow up to 3 links — but only to gridgrove.gg, chess.com, and lichess.org; other domains are still rejected to prevent spam",
      "Fixed a server-side bug that made it impossible to create or save certain pieces with the new 'Must Move If Able' option — the piece create endpoint was rejecting submissions with a database datetime error; the underlying column / value mismatch in the insert query is now corrected so all pieces save again",
      "Fixed bot games not ending when the bot won by stalemate — the game now correctly transitions to the game-over screen instead of leaving you stuck on the play page (the bot's id was failing the database winner check; the path is now sanitized and wrapped in error handling so the gameOver event always fires)",
      "Forum comments, replies, and edits now submit when you press Enter (Shift+Enter still inserts a newline)",
      "Game wizard piece placement (Step 4) now confirms the selected piece and places it when you press Enter — previously this only worked for the modal version, not the embedded panel",
      "Promoted pieces now inherit all per-game customizations from the original game type — the promoted piece picks up its checkmate/capture-loss flags, HP/AD, burn, trample, ghostwalk, attack radius, image override, and promotion-target settings exactly as they were configured in the game wizard, instead of falling back to the global piece defaults",
      "Server Stats admin tab now shows a clear error message when the endpoint isn't reachable (404, 401/403, network) so you can tell whether the backend needs a restart vs an authorization issue",
      "Old read notifications (30+ days) and very old unread notifications (90+ days) are now automatically cleaned up every 6 hours so the notifications list stays fast and responsive even for long-time players",
      "Fixed a promotion bug where the per-placement promotion override list was bypassing the 'limit promote-to-checkmate / capture-loss to original starting count' guard — players could end up promoting to a third king when they only started with two; the limit is now enforced for both the default promotion list and explicit override lists",
      "Forum create and edit pages have a fresh, modernized look with cleaner spacing, focus highlights, character counters, and a panel layout consistent with the rest of the site",
      "Forum post editing now includes a Cancel button so you can back out of an edit without saving (with a confirmation prompt if you have unsaved changes)",
      "Forum comment editing now includes a Cancel button, and clicking anywhere outside an open comment edit field will cancel the edit immediately — no need to first click inside the comment first",
      "Piece Wizard step 4 (Special Abilities) gained a 'Must Move If Able' option that forces a piece to move on its owner's turn whenever it has a legal move (great for the duck in Duck Chess); a sub-option 'Forced Move Uses an Action' lets you decide whether the forced move counts against actions per turn or is free",
      "These new must-move settings persist across piece creation, editing, and are shown on the piece detail page under Special Abilities",
      "Profile pictures and piece images that are exact duplicates of an existing upload are now reused from a single source instead of being stored twice — uploads are content-hashed within their folder, and old profile pictures are only deleted when no other user references them",
      "Fixed the admin Drafts tab not loading correctly: drafts now load reliably and pagination resets cleanly when switching between admin tabs (the bug was caused by a missing updated_at column on game types and stale state from the previously selected tab)",
      "Stalemate detection is now generalized to all pieces, not just kings — a player who has no legal moves on their turn (and isn't in check) will now correctly end the game even in games without a checkmate condition (e.g. a single pawn stuck behind an enemy pawn now ends the game)",
      "Stalemate outcome respects your win conditions: 'Stalemate Win' awards the win to the stalemated player, 'No Legal Moves' awards the win to the opponent, otherwise the game ends in a draw",
      "Fixed the 'Require all capture-flagged pieces to be captured' win condition not persisting when editing or saving a draft — the toggle now loads its previous value and survives create / edit / draft round trips",
      "Custom squares are no longer placeholders! When you place a custom square you can now toggle it to act as a Range, Promotion, and/or Control square simultaneously, with full per-square configuration",
      "Custom squares show their combined behaviors directly on the board — the indicator letter changes (e.g. R, RP, RPC) based on which behaviors are enabled",
      "Custom square combinations work in live games, on the game detail board preview, in fill-row, on edits, and in drafts",
      "The game detail page now describes each custom square and which behaviors it combines",
      "Fixed an overlap on small screens where the 'Show Details' toggle could collide with the 'Board Setup' heading on the game detail page",
      "Fixed a regression where opponent names linked to a profile page in match history rows for games against the computer — the bot opponent is no longer rendered as a clickable link",
      "Ranged attacks now count as legal moves when checking for stalemate, so a piece that can only attack at range is no longer treated as having no moves",
      "Stalemate detection now requires an explicit 'Stalemate Draw Rule' (default ON for both new and existing games) — if neither stalemate-win, no-legal-moves, nor stalemate-draw is enabled, the stuck player simply skips their turn and a notice is shown so the game keeps going",
      "Added an Email Notifications section to Preferences with a global on/off and per-type opt-out (friend requests, challenges, comments, replies, game threads, opponent moves, game chat) — opted-out types are excluded from both the email threshold and the email body",
      "Notification summary emails now include a one-click unsubscribe link at the bottom that disables future notification emails without requiring a login",
      "Notification summary emails now require more than 20 unread notifications (raised from 10) before being sent",
      "Added a Drafts tab to the admin portal showing all unfinished game drafts across users, with view-detail, open-in-wizard, and delete actions; existing Games tab now hides drafts",
      "Match history now shows both players as side-by-side cards — your card always appears first on the left; the result trophy icon is contained in the upper-left of the winner's card; a chess-piece icon (♔ or ♚) in the lower-right of each card shows which player color each person was",
      "Match history list view reverted to the original compact row layout; player 1 (white) is now always listed first followed by player 2 (black), and a small ♔/♚ icon appears inline next to each name to show player color",
      "Match history detail page (match review) always shows the player 1 card on the left and player 2 card on the right; the winner crown badge is now contained inside the top-left of the winning card, and a ♔/♚ color icon sits in the lower-right corner of each card",
    ]
  },
  {
    date: "April 18, 2026",
    title: "Promotion Overhaul, Match Review Polish & Piece Wizard Limits",
    items: [
      "Promotion target selection has moved out of the piece wizard and into the game wizard — when you place a piece that can promote, a new collapsible 'Promotion Options' section now appears in step 4 next to Combat Stats",
      "You can override the default promotion list per placement, with a paginated piece picker capped at the number of unique piece types on the board plus 8",
      "If your game uses the checkmate win condition, you can now allow a piece to promote into a checkmate piece (e.g. another king), with an optional 'cannot exceed the original starting count' guard that hides the option from the promotion modal once the player owns as many checkmate pieces as they started with",
      "The same allow/limit pair is available for win-on-capture pieces, regardless of win condition",
      "Mirroring a player's pieces in step 4 now copies these new promotion settings as well",
      "Game detail pages now describe each piece's promotion targets, including any allowance for checkmate or win-on-capture targets and any 'limit to original count' guards",
      "Sandbox now respects 'first move only' movement and capture restrictions — once a piece has moved, those moves are no longer offered, matching live-game behaviour",
      "Match review now has a true 'starting position' before the first move — using ⏮ jumps to the empty-history view, and arrow keys can step into and out of it",
      "When viewing the starting position, no row in the move history table is highlighted; pressing the right arrow then highlights the first move",
      "Grove theme background tuned to a subtly greener tint",
      "Pieces with more than 2 image variants can now actually use those extra images in real games — pick any image in the 'Choose Image' grid and it will be saved with the placement and shown everywhere (sandbox, home preview, live games, match review, promotions)",
      "Clicking Player 1 or Player 2 still resets the image to that player's default; only clicking inside the image grid creates an override",
      "When a game is saved, you'll now get a dismissible warning if you've assigned a dark image to Player 1 or a light image to Player 2",
      "Large card shadows (e.g. home preview board, feature cards, create-news panel, career listings) toned down for a cleaner, less dramatic look",
      "Step-by-step movement, capture, and ranged attack values are now capped at 8 to prevent extreme pieces from causing hover lag",
      "Custom square movement and attack are now limited to 50 squares each, with a live counter shown in the piece wizard",
      "Adding new custom squares is automatically blocked when step-by-step movement, capture, or ranged attack is set to 7 or higher (the step area already covers the entire grid), with a clear in-wizard message explaining why",
      "Updated piece wizard tooltips to document the new step-by-step and custom-square limits",
      "Piece detail pages now collapse the custom-square movement and attack lists by default when there are 10 or more squares, with a Show all / Hide toggle",
      "All dates and times across the site (last active, account creation, piece/game creation, forums, comments, news, careers, changelog, etc.) now display in your own local time, converted from a single UTC source of truth so relative ordering stays correct across users",
      "Removing the checkmate or capture win condition from a game now correctly clears any per-placement checkmate/capture flags so leftover icons no longer appear in the wizard or game detail page",
      "Sandbox now uses the same purple highlight as the piece detail page for first-move-only movement and capture squares",
      "Added Anti-Chess support: a new 'Lose-All-Pieces Win' condition lets a player win as soon as they have lost all of their pieces",
      "Added a 'Stalemate Win' condition — when enabled, a stalemated player (no legal moves and not in check) wins instead of the game being a draw",
      "Added a 'Forced Capture' gameplay rule — when enabled, if any of your pieces can capture, you must make a capturing move (any capture) on your turn",
      "All three new rules are explained on the game detail page and listed alongside existing win conditions on game library cards, match history, and live game over messages",
      "Customize Promotion Options now searches the full piece library — every piece is reachable via search and pagination, not just the first few past those already on the board",
      "Selected promotion targets now appear as a separate, always-visible chip list above the picker, with one-click removal — no more hunting through pages or search to see what you've picked",
      "Right-clicking a piece in step 4 now opens the piece selector instantly because it reuses the pieces already loaded by the placement editor instead of re-fetching them",
      "Game detail pages now render promotion-target piece names as proper links to the piece detail pages, even when those pieces aren't placed on the board",
      "Forced Capture rejections now name the exact piece, target, and capture type the server detected, so it's much easier to find the available capture (or report a false positive)",
      "Forced Capture now also recognizes ranged attacks and en passant as captures, so the rule no longer blocks valid en-passant moves or non-capturing moves when the only available capture was a ranged attack",
      "Fixed a Forced Capture false positive where extended-distance moves (like a pawn's first-move two-square advance) were treated as captures even in directions the piece can only move — not capture — through",
      "The threefold-repetition draw counter now resets when a piece takes damage but survives, so wearing down high-HP pieces no longer triggers an unintended draw",
      "Added a new home-page banner inviting players to share bugs and feedback on the forums, with a heads-up about frequent server restarts during this update period — admins can toggle it on/off and edit its text from the Site Settings tab",
      "Trimmed a large amount of console noise (Redux actions, reducers, services, hover and socket-connection logs) for a cleaner browser console",
    ]
  },
  {
    date: "April 17, 2026",
    title: "Theme Polish, Live Fixes & Better Browsing",
    items: [
      "Profile pages now open published games and pieces on their public detail pages, while drafts still jump straight into the editor",
      "Direct links to older game types on /play now load the correct game, and the game-type sidebar now supports pagination",
      "Blocked ranged attacks in live games no longer make the attacking piece appear to move before the server rejects the shot",
      "Piece detail pages now explain custom-square movement and attack patterns in plain text",
      "Clicking alternate piece images now previews that image on the piece board until you refresh or leave the page",
      "Footer section headings now link directly to Create, Play, Community, and Info",
      "Home page stats, hero buttons, and shared green/blue hover accents have been refined for a cleaner, more consistent theme across navigation and buttons",
      "Piece library cards in the grove theme now use the same darker border treatment as game library cards instead of the old blue-tinted outlines",
      "Forum Subject and Written By columns now stay left-aligned consistently across forum tables",
      "Dark panels such as profile, edit profile, and preferences sections now use softer shadows and lower-contrast borders for a cleaner look",
      "Dark cards, sections, filters, and other panel-style elements now use the same border treatment as the user profile across hubs, forums, streams, news, tutorial, and shared buttons",
    ]
  },
  {
    date: "April 16, 2026",
    title: "Game Wizard & Bug Fixes",
    items: [
      "Game sounds are now on by default for new users — no need to enable them manually",
      "Last move indicators in live games now show all moves made during a multi-action turn, not just the final move",
      "Vacated squares now use a dashed outline instead of a solid highlight, making it easier to distinguish where a piece moved from vs. where it landed",
      "Editing a published game now offers 'Copy as Draft' — creates a separate draft copy so the original game stays public and playable",
      "Game wizard header now shows 'Save as Draft' and 'Save and Exit' buttons at the top of every step for easier access",
      "Previous and Next buttons are now anchored to the bottom corners of the wizard for consistent navigation",
      "Simultaneous turns and Create anonymously options now use toggle switches with tooltips instead of checkboxes with inline text",
      "Game detail page now shows the board setup and stats above the description for a better first impression",
      "Fixed a bug where ranged units without 'fire over pieces' could appear to move through blocking pieces instead of being blocked",
      "The final checkmate move is now recorded and displayed in the match history",
      "Check (+) and checkmate (#) notation now appears on moves in the match history",
      "Correspondence games now appear in the ongoing games sections on /play and profile pages",
      "Ongoing games on /play are now split into 'Live Games' and 'Correspondence Games' sections",
      "Ongoing Games section on player profiles is now displayed above My Games for better visibility",
      "The /play page now shows the number of players currently online next to the connection indicator",
    ]
  },
  {
    date: "April 15, 2026",
    title: "Sound Effects, AI, Home Board & UI Overhaul",
    items: [
      "Home page board now features turn-based play — alternate between your pieces and the opponent's",
      "Turn indicator in the lower-left shows whose turn it is with a colored dot",
      "Hovering a piece on the home board now previews its available moves and captures with distinct colors",
      "Gold dots and orange borders indicate moves that are only available on the piece's first move",
      "Last-move highlights now use a subtle dashed outline (matching sandbox style) instead of permanent colors",
      "Clicking a different piece properly clears the previous piece's highlights",
      "First N moves restrictions are now respected on the home page board",
      "Home board panel border width now matches other panels on the page",
      "Fixed dragging pieces on the home page sometimes picking up the entire row as a chunk",
      "AI difficulty buttons in the host game modal now spread evenly across their row",
      "New distinct sound effect plays when a piece is hit but survives (HP/AD system)",
      "Sound playback length reduced to 0.6s for snappier feedback; move sounds play at 0.25s and check sounds at 0.4s for even snappier response",
      "Computer opponent now values piece exchanges more aggressively — trading a lower-value piece for a higher-value one is prioritized",
      "Sound effects now reliably play after switching back to the browser tab",
      "The last move of a game now plays its sound (capture, move, etc.) even when the game ends in checkmate",
      "Winning by capture now correctly plays the capture sound effect",
      "Check sound now plays on the first move of a multi-action turn when that move puts the opponent in check",
      "Fixed a bug where pieces with 'disable hopping for non-exact directional movement' could still hop through other pieces when calculating check and checkmate",
      "Fixed the first sound in a computer game sometimes playing at full length instead of being clipped",
      "Premoves in multi-action turn games no longer end your turn early — remaining actions are preserved",
      "King-type pieces can no longer be directly captured in multi-action games — checkmate is required",
      "Fixed 'You are in check' incorrectly showing for the moving player when they put the opponent in check mid-turn",
      "When you put the opponent in check mid-turn, a message now tells you to try to checkmate them before your turn ends",
      "Fixed the first computer move sound still sometimes playing at full length",
      "Restored the 'Ends game on checkmate' toggle in the piece placement modal of the game wizard",
      "Castling partners section now matches the width of Combat Stats and Additional Piece Settings sections",
      "Restored toggle switch styling to rounded pill shape in the game wizard",
      "Fixed pieces incorrectly showing capture-only squares as valid moves during regular turns in bot games",
      "Premoves can now target squares occupied by your own pieces — if the opponent captures your piece, your premove will recapture the attacker",
      "Premoves now correctly trigger promotion when a piece reaches a promotion square",
      "If only one promotion option is available, the piece auto-promotes without showing a modal",
      "When no valid promotion options exist, a message is shown instead of freezing the game",
      "Promotion no longer offers promotable, checkmate, or capture-loss pieces as options",
      "Premoves now play the check sound when the premove puts the opponent in check",
      "Improved connection resilience — the game automatically reconnects after server restarts or network interruptions",
      "Premoves can now target enemy checkmate pieces (they may move away before your premove executes)",
      "Offering a draw to the computer now automatically results in a draw",
      "New 'Premove Clock Cost' option in Additional Options — optionally deducts 0.1 seconds per premove instead of being free",
      "Additional Options in the host game modal now use toggle switches with helpful descriptions for each setting",
      "Toggle switch styling restored to rounded pill shape across the entire site",
      "Green theme header and footer gradients are slightly more green again while staying lighter than original",
      "Reduced duplicate API calls — site settings now load once on startup instead of per-component",
      "Game lobby lists now managed centrally for better performance",
      "Host game modal dropdowns and Play As buttons restyled for a cleaner, more consistent look",
      "Dropdown option backgrounds are now dark for better readability",
      "Additional Options panel now overlays the modal instead of expanding it",
      "Notification links for new user registrations now correctly open their profile page",
      "Change password now works properly on the Edit Profile page — enter your current and new password to update",
      "New 'Update Password' button lets you change just your password without updating other settings",
      "Password requirements are now shown as a live checklist while typing your new password",
      "New site logo and favicon — updated across browser tabs, navbar, and PWA icons",
      "Dark-themed browsers now see a lighter favicon for better visibility",
      "Navbar logo is now slightly larger with a subtle warm glow on hover",
      "Win on promotion now triggers correctly even when no valid promotion pieces exist",
      "Promotion square highlights are now a lighter, more visible purple",
      "Match history board now fits within the screen on mobile devices",
      "Match history no longer shows 'won by game completed' — all win conditions now display properly",
      "Game Details and Game Settings sections in match history are now collapsible (collapsed by default)",
      "Lichess users can now edit their profile without adding an email address",
      "New 'Show Details' toggle on the game details page — switch between a clean board view and one with all overlays (badges, dots, special squares, etc.)",
      "Fixed mobile drag-and-drop showing a duplicate ghost piece instead of lifting the original in live games",
      "Mobile touch drag-and-drop now works on all boards — home page, sandbox, piece wizard preview, game wizard piece placement, and special square placement steps",
      "Admin and owner image uploads are now auto-approved — no more 'Under Review' for your own pieces",
      "New 'Moderation' tab in the admin dashboard to review, approve, or reject flagged piece images",
      "Admins and owners can now approve pieces directly from the piece details page when images are under review",
      "Piece images that fail to load now show a matching chess piece from the built-in library as a fallback instead of blank/broken images",
      "Editing a piece's images no longer breaks pieces in active games — old image files are preserved for compatibility",
    ],
  },
  {
    date: "April 14, 2026",
    title: "Lichess Login, Spectator Fixes, Theme Cleanup & Sound Improvements",
    items: [
      "You can now sign in or register with your Lichess account",
      "Lichess login button appears on both the Login and Register pages",
      "Spectators now see both players' actual names on the chess clocks instead of '(You)'",
      "Spectators no longer see a green highlight border on the clocks",
      "The active turn indicator now correctly highlights the current player's clock for spectators",
      "Spectators can no longer click on pieces or set premoves",
      "Spectator list now properly displays when others are watching a game",
      "You can now skip steps freely in the game and piece creation wizards",
      "Clicking Create/Save with missing required fields now shows a clear prompt listing what still needs to be filled in",
      "New check sound effect for a more distinct alert",
      "Sound effects now play longer (0.8s) for better clarity",
      "Fixed a rare issue where capture sounds could be skipped during rapid play",
      "Pieces with separate attack patterns (like pawns) can now properly premove their attack squares",
      "Sound effects are now enabled by default for new visitors",
      "In-game options panel now uses a collapsible arrow instead of an X button",
      "Sound playback length reduced to 0.7s for snappier feedback",
      "Admin portal links no longer show underlines",
      "Long-pressing pieces on the home page no longer triggers the browser image menu on mobile",
      "Touch drag on mobile now shows check error messages and plays illegal move sounds, matching desktop behavior",
      "Touch drag now properly handles multi-tile piece grab offset on mobile",
      "Clicking a 'new user joined' notification now leads to that user's profile page",
      "Footer top border now matches the header bottom border color for visual consistency",
      "Green theme header and footer gradients are now more gray and slightly lighter",
      "Standard buttons no longer use gradients — flat, muted backgrounds with theme-aware borders",
      "Removed high-contrast gradients from game mode tabs, fill-row switches, and progress bars",
      "Replaced hardcoded hex colors across 10+ files with reusable CSS theme variables",
      "Special square colors (range, promotion, control, custom) are now centralized as CSS custom properties",
      "Role badges (Owner, Admin) now use shared CSS variables for consistent styling",
      "Player list avatar, rating, and link colors now use theme variables instead of hardcoded values",
      "Admin dashboard empty-state text colors replaced with theme variables",
      "Game rules now show stalemate as a draw condition when checkmate is enabled",
      "Game rules now show an insufficient material draw condition when both sides have checkmatable pieces",
      "Win conditions section now names the specific piece that must be checkmated",
      "Game rules automatically refresh when returning from editing a game type",
      "Insufficient material draw now triggers in live games when only checkmatable pieces remain",
    ],
  },
  {
    date: "April 13, 2026",
    title: "Library UX, New Abilities, Upvotes & Profile Improvements",
    items: [
      "New piece ability: Die on Capture — a piece is destroyed after it captures an enemy piece",
      "New piece ability: Attack Radius — when capturing, the piece damages all enemies within a radius of the landing square (up to 4)",
      "Attack Radius is mutually exclusive with Trample Radius — you can set one but not both",
      "Checkmate-immune pieces (e.g. kings) are immune to Attack Radius splash damage",
      "Attack Radius splash zones are highlighted when hovering a piece with the ability in game detail, live game, and game wizard",
      "Both new abilities are available in the Piece Wizard under Special Abilities with tooltips",
      "Game detail page now displays Die on Capture and Attack Radius in the Special Rules section",
      "New win condition: Win on Promotion — when enabled, a player instantly wins when their promotable piece reaches a promotion square",
      "Win on Promotion works with bot games as well",
      "Fixed image moderation model failing to load on startup",
      "Game library now displays all win conditions including No Legal Moves and Win on Promotion",
      "New filter options for No Legal Moves and Win on Promotion in the game library",
      "Upvote system: upvote your favorite games in the library and on game detail pages",
      "New 'Most Upvoted' sort option in the game library",
      "Range squares now grant a +1 bonus to all movement, capture, and attack ranges for pieces standing on them (previously visual-only)",
      "Range square bonus applies to directional, step, ratio, and additional scenario movements",
      "Match history now shows all win reasons including promotion, piece count, move limit, repetition, and agreement",
      "Upvote button moved to upper-right corner of game cards and game detail header for easier access",
      "Game cards now feature a play button that takes you directly to the play screen with that game selected",
      "Create New Game and Create New Piece buttons now appear in the header row next to the page title",
      "On smaller screens, the create button moves to its own centered row below the header",
      "My Games and My Pieces filter buttons replaced with options in the Sort By dropdown",
      "Show Pieces As toggle moved into the filter controls area on the Piece Library page",
      "My Games and My Pieces sections on profiles are now collapsible with a toggle arrow",
      "Match History section on profiles is now collapsible and no longer has extra top margin",
      "Long-pressing piece images on mobile no longer triggers the browser context menu",
      "Touch-action fixes applied to boards across home, sandbox, game wizard, match view, and game type view",
      "Emoji picker now lazy-loads emojis for faster opening and smoother scrolling",
      "Emoji category headers removed from the picker grid for a cleaner layout",
      "Admin and Owner roles can now properly edit other users' profiles",
      "Admin and Owner roles can now properly edit forum posts they didn't create",
      "Every forum post page now has a 'Back to Forums' arrow link at the top",
      "Game links in the Game Forums table no longer show underlines and have proper hover styling",
      "Create New Game and Create New Piece buttons are now anchored to the upper right with the title centered",
      "Match History section on profiles now uses the same panel styling as Ongoing Games",
      "Fixed piece drag and drop on the home page boards that stopped working on desktop",
      "Admins can now only moderate content from regular users; Owners can moderate all content including admin content",
      "Profile Bio section now uses the same card styling as other profile sections",
      "Profile card sections have tighter padding for a more compact layout",
      "My Games, My Pieces, and Match History sections are now collapsed by default on profiles",
      "Reduced spacing in friends list and ongoing games sections on profiles",
      "Create button padding and game/piece library title margins adjusted for a cleaner header",
      "Filter controls on Game Library and Piece Library pages now fit content width on larger screens",
      "Accent text color is slightly lighter across both green and blue themes for better readability",
      "Visual refresh: reduced border-radius, removed color transition animations, and dimmed overly bright borders across the site",
      "Reduced gradient contrast across all panels and cards for a more muted look",
      "More muted hover borders across the site — less aggressive accent color on hover",
      "Navigation header is now shorter (7vh) with a subtle reverse gradient (darker at bottom)",
      "Green theme header is now darker than the page background",
      "Line under the header is now dark gray instead of the theme color",
      "Home page buttons have reduced border-radius and more muted borders",
    ]
  },
  {
    date: "April 11, 2026",
    title: "Multi-Action Turns, Move Confirmation Preview & Toggle Improvements",
    items: [
      "Actions per turn now works — games with multiple actions per turn let you move or place pieces multiple times before your turn ends",
      "Correspondence move confirmation now shows your move on the board before you confirm, and reverts if you cancel",
      "Confirm/cancel move buttons no longer overflow the sidebar — text stays on one line while buttons wrap to fit",
      "Host Game modal toggle switches now properly display inline with their labels",
      "In checkmate-only games with multiple actions per turn, you can no longer capture the checkmate piece directly — it must be checkmated",
      "Mid-turn checkmate detection: if checkmate is detected before all actions are used, a message is shown and the player must complete their remaining actions",
      "Game detail page and tooltips now explain how checkmate works in multi-action games",
      "Fixed checkmate icon alignment on the game detail board",
      "Fixed multi-action correspondence games allowing unlimited moves before confirming — confirmation now happens per action",
      "Match review page now shows the computer difficulty level and no longer links to a profile for computer players",
    ]
  },
  {
    date: "April 10, 2026",
    title: "Sandbox Rules, Turn Confirmation & UI Polish",
    items: [
      "Added content moderation — offensive usernames are now blocked during registration and profile edits (Scunthorpe-safe: innocent words like 'Scunthorpe' won't be rejected)",
      "Game names, descriptions, rules, and piece descriptions are now checked for inappropriate language with real-time warnings",
      "Links and URLs are no longer allowed in game or piece descriptions",
      "Forum posts and comments are checked for offensive language before posting",
      "Maximum actions per turn is now capped at 8",
      "Uploaded piece images and profile pictures are now automatically scanned for inappropriate content",
      "Images that need manual review are queued — you'll see an 'Under Review' badge until approved",
      "Creating pieces and games now requires being logged in",
      "Fixed multi-tile pieces allowing sizes larger than 4×4",
      "Fixed games against the computer getting stuck when a player runs out of time",
      "Fixed match history not showing the computer opponent or difficulty level in some games",
      "Fixed ongoing games list not displaying the computer opponent's name correctly",
      "The site owner now receives notifications for every new game, new piece, and new user registration",
      "Updated YouTube channel link",
      "Correspondence games now have a turn confirmation step — review your move before submitting, with a toggle in game options",
      "Game options menu can now be collapsed with a hamburger button to save screen space",
      "Computer player names are no longer clickable links",
      "Sandbox now has a Game Rules section below Game Types for configuring win conditions, draw rules, and gameplay mechanics (more settings coming soon)",
      "Sandbox sidebars now paginate long lists for better performance",
      "Sandbox board is now larger on desktop screens",
      "Host Game modal: 'Play vs Computer' and 'Rated Game' are now toggle switches instead of checkboxes",
      "Host Game modal: rated games are automatically disabled when playing against the computer",
      "Host Game modal: removed redundant description text for cleaner layout",
      "Maximum board size is now enforced at 48×48 on both frontend and backend",
      "Scrollbars across the site now match the current theme",
      "Sandbox sections on mobile are now a consistent 250px height with vertical scrolling",
      "Host Game modal: labels are now left-aligned with better spacing",
      "Scrollbars are now slightly darker and wider for better visibility",
      "Sandbox piece library on mobile is now taller for easier browsing",
      "Sandbox piece library and game types now show pagination info at the top of the list",
      "Sandbox piece library on desktop is now capped at 400px with scrolling",
    ]
  },
  {
    date: "April 8, 2026",
    title: "License & Housekeeping",
    items: [
      "Added a license for public repository — source is viewable for educational purposes only",
      "Fixed garbled characters appearing in various pages and emails",
    ]
  },
  {
    date: "April 7, 2026",
    title: "Custom Square Movement & Attack in Piece Wizard",
    items: [
      "Fixed dates showing as one day ahead — all dates now correctly display in your local timezone",
      "New feature: Click squares on a grid to define custom movement and attack patterns for your pieces",
      "Custom square selection available in both Step 2 (Movement) and Step 3 (Attack) of the piece wizard",
      "Click or drag to paint multiple squares at once — click again to remove",
      "Custom squares work alongside existing directional, ratio, and step-by-step movement",
      "'Attacks like movement' automatically copies custom movement squares to attack",
      "Custom movement squares shown in teal, custom attack squares in warm orange on the preview board",
      "Custom square legend entries added to the board preview",
      "Full game engine support — custom squares work in live games, sandbox, piece detail, game detail, and AI matches",
      "Interactive preview boards: click any highlighted square to watch the piece move there, then the board smoothly re-centers",
      "Move animation works in piece wizard steps 2 & 3, edit piece wizard, and piece detail page",
      "Drag-to-move support: click and drag the piece to a highlighted square for a more natural feel",
      "Piece now pauses briefly on the destination square before the board re-centers",
      "Movement & Attack preview now shows on Step 1 of piece creation, not just when editing",
      "Custom square selector grid is now larger and easier to use",
      "Fixed custom square movement not working in sandbox when placing pieces from the library",
      "Smoother board re-center animation — fixed jerkiness on short and long moves",
      "Board now shows phantom edge squares during re-center animation for an infinite board illusion",
      "Changelog page now paginates after 5 entries to keep the page manageable",
    ]
  },
  {
    date: "April 6, 2026",
    title: "AI Improvements & UI Fixes",
    items: [
      "Computer opponent now shows 'Computer is thinking...' indicator reliably during bot games",
      "Improved AI error recovery — bot will attempt a fallback move if the engine encounters an issue",
      "Play vs Computer option now appears at the top of the host game modal for easier access",
      "Admin dashboard toggles now respond immediately to clicks",
      "Computer clock now correctly tracks thinking time",
      "Computer clock now counts down in real-time while the AI is thinking",
      "Stronger AI with deeper search, quiescence search to avoid tactical blunders, and improved position evaluation",
      "AI now detects actual piece attack lines instead of using simple proximity checks",
      "Computer now properly continues after pawn promotion",
      "Promotion dialog now shows all starting piece types, not just currently alive pieces",
      "Computer games now appear in match history with a BOT badge (no ELO impact)",
      "Fixed rare page loading errors on slow connections — pages now show a reload prompt instead of crashing",
      "Messages and sound effects are now enabled by default for new accounts",
      "Added toggle to show or hide piece badges during live games",
      "Added simultaneous turns option in the game wizard for new game types",
      "Fixed checkmate detection bug where pawns could incorrectly capture forward instead of diagonally",
      "Match history board now shows your pieces at the bottom with correct notation orientation",
      "Bot opponent now shows as 'Computer (Easy/Medium/Hard)' in match history",
      "Premoves now work during computer games",
      "Computer now actively pushes promotable pieces toward promotion when the path is clear",
      "Correspondence clocks now show hours alongside days (e.g., '3d 14h')",
      "Captured pieces section now displays approximate material value with advantage indicator",
      "Improved piece value estimation — now simulates center-of-board coverage for more accurate values (pawn ≈ 1, bishop ≈ 3, rook ≈ 5, queen ≈ 9)",
      "New 'Material Clock Penalty' option — players behind in material have their clock tick up to 3× faster",
      "New 'Material Clock Handicap' option — players behind in material have their clock tick slower, giving more time to catch up",
      "Fixed clock multiplier display showing on both players — now only appears on the affected player's clock",
      "Fixed rare server crash when a game times out during material clock calculations",
      "Clock now shows tenths of a second when under 1 minute for precise time tracking",
      "Clock multiplier now disappears when material difference is negligible",
      "Clock multiplier now updates immediately after a capture instead of waiting for next tick",
      "Improved piece value estimation for promotable pieces — pawns now valued closer to 1.0",
      "Premoves now work reliably in computer games, even when the bot responds quickly",
      "Computer opponent now detects and tries to prevent checkmate threats from the player",
      "Fixed critical checkmate detection bug — Player 2 pawns' special moves (like 2-square advance) now work correctly in all directions",
      "You can now choose to play as White, Black, or Random when starting a computer game",
      "Computer games now restore properly when refreshing the page mid-game",
      "Clock penalty/handicap now visually ticks faster or slower in real-time, not just after moves",
      "Computer no longer shuffles the same piece back and forth — prefers developing new pieces",
      "Computer plays stronger openings — favors advancing center pawns two squares and developing pieces",
      "Computer better protects high-value pieces from low-value attackers",
      "In-game chat is now private between players by default — spectators cannot see messages unless both players enable the public chat toggle",
      "Chat visibility preference (public/private for spectators) is now saved to your account and remembered for future games",
      "New 'Allow spectators to view chat' toggle in Preferences under Messaging & Chat",
    ],
  },
  {
    date: "April 5, 2026",
    title: "Changelog, Game Options & Bug Fixes",
    items: [
      "Added a public changelog page accessible from the info menu",
      "Admin dashboard now has a Settings tab to enable/disable site features like the changelog",
      "Ghost board review banner now appears above the board instead of inside it",
      "Fixed pawn capture highlighting bug — pawns no longer show red highlights on pieces directly in front",
      "Added option to show/hide board notation (rank and file labels) during live games",
      "Host game modal now has a collapsible 'Additional Options' section for cleaner layout",
    ],
  },
  {
    date: "April 3, 2026",
    title: "UI Polish & Engine Overhaul",
    items: [
      "Added piece shadow preference and improved board appearance options",
      "Password reset flow is now fully functional",
      "Trample and ghostwalk abilities have been overhauled with proper check detection and radius immunity",
      "Piece image library expanded to 3,200+ images with a paginated browser",
      "Added direct messaging, inbox, and in-game chat system",
    ],
  },
  {
    date: "April 2, 2026",
    title: "Burn Damage & Live Game Improvements",
    items: [
      "New burn damage system — pieces can deal damage over time after attacking",
      "Piece placement game mode (Othello-style) added",
      "Live game clock alignment and piece count tracker improvements",
      "Various live game UI fixes and polish",
    ],
  },
  {
    date: "April 1, 2026",
    title: "Community Redesign & Correspondence Play",
    items: [
      "Community hub redesigned with match navigation, leaderboard, and a rewritten welcome section",
      "Notifications page redesigned with themed cards and type-specific styling",
      "Correspondence game notifications and draw-before-first-move support",
      "Fixed castling info display, correspondence clock, game type links, and room cleanup in live games",
      "Email templates restored with proper UTF-8 emoji and symbol encoding",
    ],
  },
  {
    date: "March 31, 2026",
    title: "HP / AD System & Piece Stats",
    items: [
      "New HP, Attack Damage, and Regen system — pieces can take damage, heal, and regenerate over turns",
      "HP/AD overlays with badges, HP bars, damage/regen animations, and sound effects in live games",
      "Piece wizard and game wizard updated with HP/AD/Regen configuration controls",
      "Game detail page now shows piece stat breakdowns correctly",
    ],
  },
  {
    date: "March 30, 2026",
    title: "Admin Tools & Game Hosting",
    items: [
      "Admin portal expanded with delete/edit for pieces, games, forums, and news",
      "Private games section added to the play page with admin delete buttons",
      "Castling distance is now configurable per piece placement",
      "Challenge button now visible for all friends on profile pages",
      "Fixed directional hopping flag persistence and display on piece detail pages",
      "Home page stats now show correct totals instead of being capped at 20",
    ],
  },
];

const ENTRIES_PER_PAGE = 5;

const Changelog = () => {
  const { changelogEnabled, loaded } = useSelector((state) => state.siteSettings);
  const [page, setPage] = useState(0);

  const totalPages = Math.ceil(changelogData.length / ENTRIES_PER_PAGE);
  const pageEntries = changelogData.slice(page * ENTRIES_PER_PAGE, (page + 1) * ENTRIES_PER_PAGE);

  if (!loaded) {
    return (
      <div className={styles["changelog-container"]}>
        <div className={styles["changelog-header"]}>
          <h1>Changelog</h1>
        </div>
      </div>
    );
  }

  if (!changelogEnabled) {
    return (
      <div className={styles["changelog-container"]}>
        <div className={styles["changelog-disabled"]}>
          <h2>Changelog Unavailable</h2>
          <p>The changelog is currently hidden. Check back later.</p>
        </div>
      </div>
    );
  }

  return (
    <div className={styles["changelog-container"]}>
      <div className={styles["changelog-header"]}>
        <h1>Changelog</h1>
        <p className={styles["subtitle"]}>Recent updates and improvements to GridGrove</p>
      </div>

      {pageEntries.map((entry, i) => (
        <div key={i} className={styles["changelog-entry"]}>
          <div className={styles["entry-date"]}>{entry.date}</div>
          <div className={styles["entry-title"]}>{entry.title}</div>
          <ul className={styles["entry-list"]}>
            {entry.items.map((item, j) => (
              <li key={j}>{item}</li>
            ))}
          </ul>
        </div>
      ))}

      {totalPages > 1 && (
        <div className={styles["pagination"]}>
          <button
            className={styles["page-btn"]}
            disabled={page === 0}
            onClick={() => setPage(p => p - 1)}
          >
            ← Newer
          </button>
          <span className={styles["page-info"]}>
            Page {page + 1} of {totalPages}
          </span>
          <button
            className={styles["page-btn"]}
            disabled={page >= totalPages - 1}
            onClick={() => setPage(p => p + 1)}
          >
            Older →
          </button>
        </div>
      )}
    </div>
  );
};

export default Changelog;
