export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USER = "GET_USER";
export const CLEAR_PLAYER_PAGE = "CLEAR_PLAYER_PAGE";
export const LIST_USERS = "LIST_USERS";
export const LIST_USERS_FAIL = "LIST_USERS_FAIL";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_ADMIN = "DELETE_USER_ADMIN";
export const REMOVE_USERS = "REMOVE_USERS";
export const EDIT_SUCCESS = "EDIT_SUCCESS";
export const EDIT_SUCCESS_ADMIN = "EDIT_SUCCESS_ADMIN";
export const EDIT_FAIL = "EDIT_FAIL";
export const RESET_EDIT = "RESET_EDIT";

export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";
export const ALL_FORUMS = "ALL_FORUMS";
export const ALL_FORUMS_FAILURE = "ALL_FORUMS_FAILURE";
export const GET_FORUM_SUCCESS = "GET_FORUM_SUCCESS";
export const GET_FORUM_FAILURE = "GET_FORUM_FAILURE";
export const FIRST_FORUMS_RENDER = "FIRST_FORUMS_RENDER";

export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const COMMENT_EDIT_SUCCESS = "COMMENT_EDIT_SUCCESS";
export const COMMENT_EDIT_FAILURE = "COMMENT_EDIT_FAILURE";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";
export const DELETE_FORUM = "DELETE_FORUM";
export const DELETE_FORUM_FAILURE = "DELETE_FORUM_FAILURE";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAILURE = "LIKE_FAILURE";
export const DELETE_LIKE = "DELETE_LIKE";

export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const NEWS_FAILURE = "NEWS_FAILURE";
export const ALL_NEWS = "ALL_NEWS";
export const ALL_NEWS_FAILURE = "ALL_NEWS_FAILURE";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILURE = "GET_NEWS_FAILURE";
export const EDIT_NEWS_SUCCESS = "EDIT_NEWS_SUCCESS";
export const EDIT_NEWS_FAILURE = "EDIT_NEWS_FAILURE";

export const LIST_PIECES = "LIST_PIECES";
export const LIST_PIECES_FAIL = "LIST_PIECES_FAIL";
export const REMOVE_PIECES = "REMOVE_PIECES";

export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const CREATE_GAME_FAIL = "CREATE_GAME_FAIL";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_FAIL = "GET_GAMES_FAIL";
export const UPDATE_GAME_SUCCESS = "UPDATE_GAME_SUCCESS";
export const UPDATE_GAME_FAIL = "UPDATE_GAME_FAIL";
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS";
export const DELETE_GAME_FAIL = "DELETE_GAME_FAIL";

export const UPDATE_USER_PREFERENCES = "UPDATE_USER_PREFERENCES";
export const DELETE_NEWS = "DELETE_NEWS";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";
// Friends
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAIL = "GET_FRIENDS_FAIL";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAIL = "ADD_FRIEND_FAIL";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAIL = "REMOVE_FRIEND_FAIL";
export const GET_ONLINE_FRIENDS_SUCCESS = "GET_ONLINE_FRIENDS_SUCCESS";
export const GET_ONLINE_FRIENDS_FAIL = "GET_ONLINE_FRIENDS_FAIL";
export const SET_ONLINE_USERS = "SET_ONLINE_USERS";

// Friend Requests
export const GET_INCOMING_REQUESTS_SUCCESS = "GET_INCOMING_REQUESTS_SUCCESS";
export const GET_INCOMING_REQUESTS_FAIL = "GET_INCOMING_REQUESTS_FAIL";
export const GET_OUTGOING_REQUESTS_SUCCESS = "GET_OUTGOING_REQUESTS_SUCCESS";
export const GET_OUTGOING_REQUESTS_FAIL = "GET_OUTGOING_REQUESTS_FAIL";
export const ACCEPT_FRIEND_REQUEST_SUCCESS = "ACCEPT_FRIEND_REQUEST_SUCCESS";
export const ACCEPT_FRIEND_REQUEST_FAIL = "ACCEPT_FRIEND_REQUEST_FAIL";
export const DECLINE_FRIEND_REQUEST_SUCCESS = "DECLINE_FRIEND_REQUEST_SUCCESS";
export const DECLINE_FRIEND_REQUEST_FAIL = "DECLINE_FRIEND_REQUEST_FAIL";
export const CANCEL_FRIEND_REQUEST_SUCCESS = "CANCEL_FRIEND_REQUEST_SUCCESS";
export const CANCEL_FRIEND_REQUEST_FAIL = "CANCEL_FRIEND_REQUEST_FAIL";
